# Generated by Django 5.0.7 on 2024-08-03 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="فرمت شماره همراه صحیح نیست.",
                                regex="^0[0-9]{10}$",
                            )
                        ],
                        verbose_name="شماره همراه",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, null=True, verbose_name="نام"),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="نام خانوادگی"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="فرمت ایمیل معتبر نیست.",
                                regex="^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$",
                            )
                        ],
                        verbose_name="ایمیل",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
